spring:
  application:
    name: velocity-api
  datasource:
    url: jdbc:postgresql://localhost:5432/velocity
    username: admin
    password: ${POSTGRES_PASSWORD:password}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    open-in-view: false
  liquibase:
    contexts: dev
  data:
    web:
      pageable:
        max-page-size: 50

springdoc:
  swagger-ui:
    path: /api/swagger-ui.html
  api-docs:
    path: /api/api-docs

pricing:
  daily-rate: 50.00

server:
  port: 8080